# -*- coding: utf-8 -*-
"""SecretAuction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s2DibnRPCDta8sbGLNvVc9wqCeAq8MKW
"""

bids = {}
bidding_finished = False

def find_highest_bidder(bidding_record):
  highest_bid = 0
  winner = ""
  for bidder in bidding_record:
    bid_amount = bidding_record[bidder]
    if bid_amount > highest_bid:
      highest_bid = bid_amount
      winner = bidder
  print(f"The Winner is {winner}! They won a bid of ${highest_bid}.")

while not bidding_finished:
  name = input("Please enter your name:\n")
  price = int(input("Please enter the amount for which you want to bid: \n$"))
  bids[name] = price
  should_continue = input("Are there any other bidder? Type 'yes'/'no'.").lower()
  if(should_continue == "no"):
    find_highest_bidder(bids)
    bidding_finished = True
  else:
    bidding_finished = False